moduledir "contrib"

mod 'puppetlabs/apt'
mod 'puppetlabs/aws'
mod 'puppetlabs/concat'
mod 'puppetlabs/docker_platform'
mod 'puppetlabs/firewall'
mod 'puppetlabs/java'
mod 'puppetlabs/mysql'
mod 'puppetlabs/puppet_agent'
mod 'puppetlabs/reboot'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'

mod 'jfryman/nginx'
mod 'zanloy/ohmyzsh'
mod 'mayflower/php'
mod 'nanliu/staging'
mod 'arnoudj/sudo'
mod 'maestrodev/wget'
