mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'puppetlabs/aws'
mod 'puppetlabs/concat'
mod 'puppetlabs/firewall'
mod 'puppetlabs/gcc'
mod 'puppetlabs/git'
mod 'puppetlabs/inifile'
mod 'puppetlabs/java'
mod 'puppetlabs/ntp'
mod 'puppetlabs/pe_gem'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/reboot'
mod 'puppetlabs/ruby'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'

mod 'saz/ssh'
mod 'saz/rsyslog'
mod 'saz/timezone'
mod 'arnoudj/sudo'
mod 'jethrocarr/hostname'
mod 'maestrodev/wget'
mod 'zanloy/ohmyzsh'

mod 'abrader/gms'
mod 'croddy/make'
mod 'stahnma/epel'
mod 'gentoo/portage'

mod 'puppet/puppetboard'
mod 'jamtur01/httpauth'

