#!/usr/bin/env ruby

require 'rubygems' if RUBY_VERSION < '1.9.0'
require 'aws-sdk'
require 'net/http'

hostname = ENV['HOSTNAME']
domain = ENV['DOMAIN']
zone = ENV['ZONE']
ttl = ENV['TTL'].to_i
type = ENV['TYPE']
target = ENV['TARGET']

AWS.config({
  :access_key_id => ENV['AWS_ACCESS_KEY'],
  :secret_access_key => ENV['AWS_SECRET_KEY']
})

if ( target == 'local-hostname ' || target == 'local-ipv4')
  metadata_endpoint = 'http://169.254.169.254/latest/meta-data/'
  target = Net::HTTP.get( URI.parse( metadata_endpoint + target ) )
end

records = [{
  :alias => [ hostname, domain, '' ] * '.',
  :target => target
}]

rrsets = AWS::Route53::HostedZone.new(zone).rrsets

case ARGV[0]
when 'start', 'restart'
  `touch /var/lock/subsys/ec2hostname`
  records.each{ |record|
    rrset = rrsets[
      record[ :alias ],
      type
    ]

    rrset.delete if rrset.exists?

    rrset = rrsets.create(
      record[ :alias ],
      type,
      :ttl => ttl,
      :resource_records => [
        { :value => record[ :target ] }
      ]
    )
  }
  exit 0
when 'stop'
  records.each{ |record|
    rrset = rrsets[
      record[ :alias ],
      type
    ]

    rrset.delete if rrset.exists?
  }
  exit `rm -f /var/lock/subsys/ec2hostname`
when 'status'
  if File.exists?('/var/lock/subsys/ec2hostname')
    puts "Running"
    exit 0
  else
    puts "Stopped"
    exit 3
  end
end

puts "Valid commands are start, restart, stop, and status"
exit 3
